<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NoResultException;

/**
 * EntityUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityUpdateRepository extends \Doctrine\ORM\EntityRepository
{

    public function lastUpdatedUsers()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('u.lastupdateddate')
            ->from('AppBundle:EntityUpdate','u')
            ->orderBy('u.lastupdateddate','desc')
            ->setMaxResults(1);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
