<?php

namespace AppBundle\Repository;
use AppBundle\Entity\User;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\NoResultException;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{

    public function namesOfProducts()
    {
        $em = $this->getEntityManager();

        $qb = $em->createQueryBuilder();

        $qb->select('p.id','p.name')
            ->from('AppBundle:Product', 'p');

        $result = $qb->getQuery()
                     ->getResult();

        try{

            return $result;

        }catch (NoResultException $e){

            return $e;
        }


    }

    /**
     * @param $id
     */
    public function productDetails($id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('p')
            ->from('AppBundle:Product', 'p')
            ->where('p.id='.$id);

       $result =  $qb->getQuery()
                     ->getResult();

       try{

           return $result;

       }catch (NoResultException $e){

           return $e;

       }
    }
}
