<?php

namespace AppBundle\Repository;
use Doctrine\ORM\NoResultException;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function listOfRelatedUsers($id)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('u')
            ->from('AppBundle:User', 'u')
            ->where('u.client ='.$id);

        $result = $qb->getQuery()
                     ->getResult();

        try{

            return $result;

        }catch (NoResultException $e){

            return null;

        }


    }

    /**
     * Retrieve a user related to a client
     *
     * @param $id
     *
     */
    public function deleteUserPerClient($id = null, $username = null )
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('u')
            ->from('AppBundle:User', 'u');

        try{

            $qb->where('u.id ='.$id);

            $result = $qb->getQuery()
                         ->getResult();

            return $result;

        }catch (NoResultException $e){

            return $e;
        }
    }
}
